name: publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Install python ${{ matrix.python-version }}
        run: |
        echo "Install"
      - name: Install dependencies
        run: |
          echo "deps"
      - name: Lint with black
        run: |
          echo "lint"
      - name: Lint with pylint
        run: |
          echo "pylint"
      - name: Check typing with mypy
        run: |
          echo "typing"
      - name: Unittest with testslide
        run: |
          echo "Unittest"
      - name: Integration test with Redfish Emulator
        run: |
          echo "Integration Testing"
      - name: Build sdist and wheel
        run: |
          echo "Build package"
      - name: Publish Package
        run: |
          echo "Publish to PyPI"
