name: publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Install python
        run: |
          echo "Install"
      - name: Install dependencies
        run: |
          echo "deps"
      - name: Lint with black
        run: |
          echo "lint"
      - name: Lint with pylint
        run: |
          echo "pylint"
      - name: Check typing with mypy
        run: |
          echo "typing"
      - name: Build sdist and wheel
        run: |
          echo "Build package"
  unittest:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Unittest with testslide
        run: |
          echo "Unittest"
  integration_test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Integration test with Redfish Emulator
        run: |
          echo "Integration Testing"
  publish:
    needs: [unittest, integration_test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Publish Package
        run: |
          echo "Publish to PyPI"
